language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

before_script:
  - composer install --prefer-source

after_script:
  - php vendor/bin/coveralls -v 

before_install:
  - composer self-update
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-9.90.tar.gz
  - tar -zxvf Image-ExifTool-9.90.tar.gz
  - cd Image-ExifTool-9.90 && perl Makefile.PL && make test && sudo make install
  - cd .. && rm -rf Image-ExifTool-9.90
